version: "3.8"
services:
    pgadmin:
        image: dpage/pgadmin4
        restart: always
        depends_on:
            - database
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root
        ports:
            - 5050:80
    database:
        image: postgres
        restart: always
        depends_on:
            - php
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        ports:
            - "5432:5432"
        volumes:
            - ./docker/postgres:/var/lib/postgresql/data
    php:
        build: .devcontainer/php
        restart: always
        environment:
            APP_ENV: ${APP_ENV}
