version: "3.8"
services:
    pgadmin:
        image: dpage/pgadmin4
        restart: always
        depends_on:
            - database
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root
        ports:
            - 5050:80
    database:
        image: postgres
        restart: always
        depends_on:
            - php
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: test_db
        ports:
            - "5432:5432"
    php:
        build: .devcontainer/php
